name: Deploy to Github.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ESIPFED_ACCESS_TOKEN }}

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: test build of website
        if: github.ref != 'refs/heads/main'
        run: |
          mkdocs build

      - name: deploy to github.io
        if: github.ref == 'refs/heads/main'
        run: |
          mkdocs gh-deploy --force
